spring:
  application.name: consumer-service
  kafka:
    consumer:
      bootstrap-servers: 'localhost:9092'
      group-id: sampleGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

server:
  port: 8081